//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingoApi.Data.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public long Id { get; set; }
        public long IdBooking { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirtDate { get; set; }
        public string Genre { get; set; }
        public string Identification { get; set; }
        public string IdentificationType { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}
