//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingoApi.Data.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public int IdCity { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public short Stars { get; set; }
        public string Location { get; set; }
        public short Tax { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    
        public virtual City City { get; set; }
    }
}
