//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingoApi.Modules.BookingClient {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BookingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookingResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingoApi.Modules.BookingClient.BookingResource", typeof(BookingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have a full name applicant.
        /// </summary>
        internal static string ApplicantRequired {
            get {
                return ResourceManager.GetString("ApplicantRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have a contact name.
        /// </summary>
        internal static string ContactNameRequired {
            get {
                return ResourceManager.GetString("ContactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have a contact phone.
        /// </summary>
        internal static string ContactPhoneRequired {
            get {
                return ResourceManager.GetString("ContactPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The check-in date cannot be longer than the check-out date.
        /// </summary>
        internal static string DatesNotValid {
            get {
                return ResourceManager.GetString("DatesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have an email.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have a departure date.
        /// </summary>
        internal static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests must have an email.
        /// </summary>
        internal static string GuesEmailRequired {
            get {
                return ResourceManager.GetString("GuesEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests must have a birtdate.
        /// </summary>
        internal static string GuestBirtRequired {
            get {
                return ResourceManager.GetString("GuestBirtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests must have a genre.
        /// </summary>
        internal static string GuestGenreRequired {
            get {
                return ResourceManager.GetString("GuestGenreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest mus have an identification.
        /// </summary>
        internal static string GuestIdRequired {
            get {
                return ResourceManager.GetString("GuestIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests must have an identification type.
        /// </summary>
        internal static string GuestIdTypeRequired {
            get {
                return ResourceManager.GetString("GuestIdTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests must have a last name.
        /// </summary>
        internal static string GuestLastNRequired {
            get {
                return ResourceManager.GetString("GuestLastNRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests must have a first name.
        /// </summary>
        internal static string GuestNameRequired {
            get {
                return ResourceManager.GetString("GuestNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests must have an phone number.
        /// </summary>
        internal static string GuestPhoneRequired {
            get {
                return ResourceManager.GetString("GuestPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hotel found for this booking.
        /// </summary>
        internal static string HotelNotFound {
            get {
                return ResourceManager.GetString("HotelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have a hotel.
        /// </summary>
        internal static string HotelRequired {
            get {
                return ResourceManager.GetString("HotelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hotels found for the search criteria, try with more guests or another date.
        /// </summary>
        internal static string HotelsNotFound {
            get {
                return ResourceManager.GetString("HotelsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No reservations found.
        /// </summary>
        internal static string NoBookingsFound {
            get {
                return ResourceManager.GetString("NoBookingsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking is not valid.
        /// </summary>
        internal static string NotValidBooking {
            get {
                return ResourceManager.GetString("NotValidBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The guest is not valid.
        /// </summary>
        internal static string NotValidGuest {
            get {
                return ResourceManager.GetString("NotValidGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} The room has a reservation between the dates {1} and {2}.
        /// </summary>
        internal static string RoomNoAvailableIntro {
            get {
                return ResourceManager.GetString("RoomNoAvailableIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The room is not available. .
        /// </summary>
        internal static string RoomNotAvailable {
            get {
                return ResourceManager.GetString("RoomNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No room found for this booking.
        /// </summary>
        internal static string RoomNotFound {
            get {
                return ResourceManager.GetString("RoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have a room.
        /// </summary>
        internal static string RoomRequired {
            get {
                return ResourceManager.GetString("RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No rooms found for the search criteria, try with more guests or another date.
        /// </summary>
        internal static string RoomsNotFound {
            get {
                return ResourceManager.GetString("RoomsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The booking must have an entry date.
        /// </summary>
        internal static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
    }
}
